#!/bin/sh

if test -e "$HOME"/.config/firstboot-done; then
  exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing filtered Flathub repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
  zenity --error --text="Removing filtered Flathub repository failed"
  exit 1
fi
echo "05"

echo "# Enabling Flathub repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
  zenity --error --text="Adding Flathub repository failed"
  exit 1
fi
echo "10"

echo "# Replacing Fedora Flatpaks (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
  zenity --error --text="Replacing Fedora Flatpaks failed"
  exit 1
fi
echo "50"

echo "Removing preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
  zenity --error \
    --text="Removing preinstalled flatpaks failed"
  exit 1
fi
echo "55"

echo "# Removing Fedora Flatpak repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
  zenity --error --text="Removing Fedora Flatpak repository failed"
  exit 1
fi
echo "60"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Firefox failed"
  exit 1
fi
echo "70"

echo "# Installing 1Password"
/usr/bin/flatpak install --user --noninteractive https://downloads.1password.com/linux/flatpak/1Password.flatpakref
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Spotify failed"
  exit 1
fi
echo "80"

echo "# Installing Visual Studio Code"
/usr/bin/flatpak install --user --noninteractive flathub com.visualstudio.code
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Visual Studio Code failed"
  exit 1
fi
echo "90"

echo "# Installing Spotify"
/usr/bin/flatpak install --user --noninteractive flathub com.spotify.Client
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Spotify failed"
  exit 1
fi
echo "100"

mkdir -p "$HOME"/.config/
touch "$HOME"/.config/firstboot-done
) |
  zenity --progress --title="Fedora Silverblue Desktop Setup" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
  zenity --error --text="Setup error, check logs"
fi
