#!/bin/sh

if test -e $HOME/.config/firstboot-done; then
  exit 0
fi

(
echo "# Waiting for Internet connection"
until ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing filtered Flathub repository"
flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
  zenity --error --text="Removing filtered Flathub repository failed"
  exit 1
fi
echo "05"

echo "# Enabling Flathub repository"
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
  zenity --error --text="Adding Flathub repository failed"
  exit 1
fi
echo "10"

echo "# Replacing Fedora Flatpaks (this may take a while)"
flatpak install --user --noninteractive org.gnome.Platform//43
flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1)
if [ "$?" != 0 ] ; then
  zenity --error --text="Replacing Fedora Flatpaks failed"
  exit 1
fi
echo "50"

echo "Removing preinstalled system Flatpaks"
flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
  zenity --error \
    --text="Removing preinstalled system Flatpaks failed"
  exit 1
fi
echo "80"

echo "Removing unnecessary Flatpaks"
flatpak remove --user --noninteractive org.fedoraproject.MediaWriter org.gnome.Connections org.gnome.Contacts org.gnome.Maps
if [ "$?" != 0 ] ; then
  zenity --error \
    --text="Removing unnecessary Flatpaks failed"
  exit 1
fi
echo "80"

echo "# Removing Fedora Flatpak repository"
flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
  zenity --error --text="Removing Fedora Flatpak repository failed"
  exit 1
fi
echo "85"

echo "# Installing Firefox"
flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Firefox failed"
  exit 1
fi
echo "90"

echo "# Installing 1Password"
flatpak install --user --noninteractive https://downloads.1password.com/linux/flatpak/1Password.flatpakref
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing 1Password failed"
  exit 1
fi
echo "95"

echo "# Installing Spotify"
flatpak install --user --noninteractive flathub com.spotify.Client
if [ "$?" != 0 ] ; then
  zenity --error --text="Installing Spotify failed"
  exit 1
fi
echo "100"
) |
  zenity --progress --title="Fedora Silverblue Flatpak Setup" --percentage=0 --auto-close --no-cancel --width=300

touch $HOME/.config/firstboot-done

if [ "$?" != 0 ] ; then
  zenity --error --text="Setup error, check logs"
fi
